### ISSUE TITLE
LemonBench does not work with sh

### ISSUE THREAD

**Issue by wpyoga** [LemonBench/LemonBench#2]
Hello! I've just discovered your script from a Chinese website. I tried it out, it seems to run fine with bash, but not with plain sh:
```
william@31:~$ sh LemonBench.sh 
LemonBench.sh: 2808: [[: not found

```
I've also checked the source using a tool called `shellcheck` and looked at the code -- it's not difficult to convert it to be POSIX-compatible. So, may I just go ahead and submit a PR?

Thanks!

**Comment by iLemonra1n** [comment]
Codebase Outdated. Closing old Issues.
