### ISSUE TITLE
双路服务器核心/线程数异常，跑分异常

### ISSUE THREAD

**Issue by EEddeenn** [LemonBench/LemonBench#4]
Environments：Debian 12 on arm / 2*Hi1616 / Taishan 2280(100) / LemonBench v3.0

Expected result:  
CPU Specifications:		**2 Physical CPUs, 64 Total Cores, 64 Total Threads**

Outputs:

-> System Information

 CPU Model Name:		Cortex-A72
 CPU Cache Size:		L1: 2.00 MB / L2: 16.00 MB / L3: 64.00 MB
 CPU Specifications:		**2 Physical CPUs, 32 Total Cores, 32 Total Threads**
 Virtualization Ready:		Yes (Based on unknown)
 Virtualization Type:		Dedicated
 Memory Usage:			947.51 MiB / 31.20 GiB
 Swap Usage:			0 KiB / 977.00 MiB
 Disk Usage:			2.15 GiB / 914.38 GiB
 Boot Disk:			/dev/sda2
 OS Release:			Debian GNU/Linux 12 (bookworm) (aarch64)
 Kernel Version:		6.1.0-10-arm64

-> CPU Performance Test (Fast mode, 1-Pass @ 5sec)

 1 Thread(s) Test:		2345.24 Scores (1.00x)
 **32 Thread(s) Test:		74605.76 Scores (31.81x)**

**Comment by iLemonra1n** [comment]
最开始做这段代码适配的时候，手里没有多路CPU的测试平台，确实没有考虑到这种特殊情况

计划修复（我尝试找一个双路平台做适配测试

**Comment by iLemonra1n** [comment]
本地没有双路服务器环境，使用VMware Workstation进行模拟，尝试修复
应该能够解决问题
