### ISSUE TITLE
BenchFunc_DepProcess_DepInst(): Dep Failed ( centos 7) 

### ISSUE THREAD

**Issue by Ros-ua** [LemonBench/LemonBench#6]
curl: (35) Peer reports incompatible or unsupported protocol version.
tar: /tmp/speedtest.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
chmod: cannot access '/tmp/speedtest': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2929k  100 2929k    0     0  8951k      0 --:--:-- --:--:-- --:--:-- 8932k
BenchFunc_DepProcess_DepInst(): Dep Failed

**Comment by iLemonra1n** [comment]
CentOS 7 maybe package too old?

Try this:

`yum update -y nss curl libcurl`
